environment:
  matrix:
    - PYTHON: "C:\\Miniconda"
    - PYTHON: "C:\\Miniconda36"
    - PYTHON: "C:\\Miniconda36-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda install numpy==1.13 matplotlib jupyter pytest pywinpty
  - pip install nengo

build: false  # Not a C# project

test_script:
  - python setup.py -q install
  - python setup.py test --addopts "nengo_spa -v --durations=20"
