# Automatically generated by nengo-bones, do not edit this file directly

import io
import pathlib
import runpy

try:
    from setuptools import find_packages, setup
except ImportError:
    raise ImportError(
        "'setuptools' is required but not installed. To install it, "
        "follow the instructions at "
        "https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py"
    )


def read(*filenames, **kwargs):
    encoding = kwargs.get("encoding", "utf-8")
    sep = kwargs.get("sep", "\n")
    buf = []
    for filename in filenames:
        with io.open(filename, encoding=encoding) as f:
            buf.append(f.read())
    return sep.join(buf)


root = pathlib.Path(__file__).parent
version = runpy.run_path(str(root / "nengo_spa" / "version.py"))["version"]

install_req = [
    "nengo @ git+https://github.com/nengo/nengo.git@fix-numpy",
    "numpy>=2.2.5",
]
docs_req = [
    "jupyter<=1.1.1",
    "matplotlib>=2.0,<=3.9.4",
    "nbsphinx>=0.8.11,<=0.9.7",
    "nengo_sphinx_theme<=20.9",
    "numpydoc>=1.4.0",
]
optional_req = [
    "scipy>=1.4.1,<=1.13.1",
    "scikit-learn<=1.6.1",
]
tests_req = [
    "jupyter>=1.0.0,<=1.1.1",
    "matplotlib>=2.0,<=3.9.4",
    "nbformat>=5.0.7,<=5.10.4",
    "pytest>=3.6,<=8.3.5",
    "pytest-plt<=1.1.1",
    "pytest-rng<=1.0.0",
]

setup(
    name="nengo-spa",
    version=version,
    author="Applied Brain Research",
    author_email="info@appliedbrainresearch.com",
    packages=find_packages(),
    url="https://www.nengo.ai/nengo-spa",
    include_package_data=True,
    license="GNU General Public License, version 2",
    description="An implementation of the Semantic Pointer Architecture for Nengo",
    long_description=read("README.rst", "CHANGES.rst"),
    zip_safe=False,
    install_requires=install_req,
    extras_require={
        "all": docs_req + optional_req + tests_req,
        "docs": docs_req,
        "optional": optional_req,
        "tests": tests_req,
    },
    python_requires=">=3.8, <=3.9",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Framework :: Nengo",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
