[pytest]
addopts = -p nengo.tests.options
norecursedirs = .* *.egg build dist docs *.analytics *.logs *.plots
markers =
    example: Mark a test as an example.
    noassertions: Mark a test without assertions. It will only be run if plots or analytics data are produced.
    slow: Mark a test as slow to skip it per default.

[tox]
envlist = py27,py34,py35,py36,static
setenv =
    PIP_USE_MIRRORS=true

[testenv]
deps =
    -rrequirements.txt
    -rrequirements-test.txt
commands = py.test {posargs} {envsitepackagesdir}/nengo_spa

[testenv:static]
deps =
     flake8
     pylint
commands =
     flake8 -v nengo_spa
     pylint nengo_spa
